dbtv1: null
sqlpro:  
  target: dev
  outputs:
    dev:   
      type: mysql
      server: test-airbyte-mysql-2.cluster-caluryjlxuvh.us-east-1.rds.amazonaws.com
      port: 3306
      schema: test_airbyte
      username: admin
      password: TestAirByte
      ssl_disabled: True


